version: '3.3'
services:
  db:
    image: arm64v8/mysql
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password4root
      MYSQL_DATABASE: lessondb
      MYSQL_USER: userdev1
      MYSQL_PASSWORD: password4dev1
  phpmyadmin:
    depends_on:
      - db
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
networks:
  wpsite:
volumes:
  db_data: